DROP TABLE IF EXISTS Theater;
DROP TABLE IF EXISTS Screen;
DROP TABLE IF EXISTS Screening;
DROP TABLE IF EXISTS User;

CREATE TABLE Theater (
    TheaterID INT NOT NULL,
    Location VARCHAR(255) NOT NULL,
    NumScreens INT,
    PRIMARY KEY (TheaterID)
);

CREATE TABLE Showing (
    ShowID INT NOT NULL,
    MovieID INT NOT NULL,
    TheaterID INT NOT NULL,
    Time DATETIME NOT NULL,
    Price FLOAT(7,2) NOT NULL,
    PRIMARY KEY (ShowID)
);

CREATE TABLE User (
    EMail VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    PhNo VARCHAR(15) NOT NULL,
    DOB DATE,
    PRIMARY KEY (EMail)
);